version: '3.8'

services:
    php:
        image: rr-example
        depends_on:
          - rabbitmq
        build:
            context: .
        # command: "rr serve -c rr.yaml -p"
        command: "tail -f /dev/null"
        ports:
            -  8090:8090
            -  9004:9004
        volumes:
            -  ./:/var/www/html
        environment:
            - NUM_POLLERS=8
            - NUM_WORKERS=4

    nginx:
        image: nginx:1.24
        ports:
            -  8091:8091
        depends_on:
            - php
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf

    rabbitmq:
        image: rabbitmq:3.11-management-alpine
        ports:
            - 5673:5672
            - 15673:15672
