version: '3'

metrics:
    address: '0.0.0.0:9254'

rpc:
    listen: 'tcp://127.0.0.1:6001'

server:
    command: 'php worker.php'


amqp:
    addr: 'amqp://guest:guest@rabbitmq:5672'

logs:
    level: debug
    mode: development
    output: stdout

jobs:
    num_pollers: 8
    parallelism: 8
    pool:
        num_workers: 4
        max_jobs: 500
        allocate_timeout: 30s
        reset_timeout: 10s
        destroy_timeout: 10s
        supervisor:
            max_worker_memory: 246
            exec_ttl: 300s
    consume:
        - amqp_message_accumulator
    pipelines:
        amqp_message_accumulator:
            driver: boltdb
            config:
                prefetch: 1
                priority: 10
                file: /tmp/amqp_message_buffer.db
        messages:
            driver: amqp
            config:
                queue: messages
                prefetch: 10
                priority: 10
                redial_timeout: 10
                routing_key: messages
                durable: true
                exchange_durable: true
                consume_all: true
                requeue_on_fail: false
